### ISSUE TITLE
Can't install on macos - needs tensorflow version 2.1.0

### ISSUE THREAD

**Issue by kdg862** [baigouy/EPySeg#1]
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.1.0 (from epyseg) (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==2.1.0 (from epyseg)

I don't think macos is on version 2.1.0 yet: https://anaconda.org/anaconda/tensorflow

**Comment by baigouy** [comment]
Thanks a lot, I did not know this MacOs subtility. The latest version (0.1.8) should now be compatible with anaconda mac (i.e. with tf 2.0.0).
