### ISSUE TITLE
GUI window not resizeable

### ISSUE THREAD

**Issue by amichaut** [baigouy/EPySeg#3]
The GUI window is too large and isn't resizeable. As a result, it is impossible to access all the elements in the GUI. 
<img width="1440" alt="Capture d’écran 2021-03-21 à 14 32 52" src="https://user-images.githubusercontent.com/11176618/111906725-57cdf980-8a52-11eb-93d6-f736c5ba6e7b.png">

Configuration: 
MacOS 10.15.7
Python 3.7.10

**Comment by baigouy** [comment]
Thanks for report. The issue should be fixed in v0.1.21 I just pushed to github and pypi.
