### ISSUE TITLE
Move to Python 3.8

### ISSUE THREAD

**Issue by jo-mueller** [baigouy/EPySeg#5]
Hi @baigouy ,

do you think it would maybe be possible to release epyseg for Python 3.8 environments? It say in `setup.py`:

```
python_requires='>=3.6, <=3.8' # tensorflow is now supported by python 3.8
```
which sounds like 3.8 is principally allowed, yet pip does not allow downloading it. Any chance for updates here?

Best, Johannes

**Comment by baigouy** [comment]
Hi @jo-mueller 

Sorry for the late reply, I'll add support for 3.8 this week.

best,

B
