### ISSUE TITLE
Problems detected. The first image could not be loaded. Please check your files and repeat step 8.

### ISSUE THREAD

**Issue by jesslmoore** [baigouy/EPySeg#8]
I'm trying to run EPySeg through Google Colab, and I'm running into an issue during step 9. When I go to segment images that I was able to segment a year ago, I am getting the following error message: 

originals n= 2
first original image

Problems detected. The first image could not be loaded. Please check your files and repeat step 8.

Are there image requirements that I am unaware of?

The images are 8 bit TIFF files.

**Comment by baigouy** [comment]
The problem should be fixed with the new version of the tool. Sorry for the inconvenience this bug it may have caused.
